[package]
name = "solidc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped-tls = "1.0.0"
bimap = "0.6.2"
backtrace = "0.3.64"